### PR TITLE
Expose the executing trigger instance

### PR DESCRIPTION
**Pull request by Cupelt**
this is a little change, user can access trigger object.
It might not be good for security, but its increase users df, i guess

and The above PR may be used for "sync invTrigger vars form previous Task" that we are working on additionally.

`#GUI "invTrigger", true` <- vars sync status

\+ I did PR for now, but where should I add the test case? It's hard because there's no example..

### CODE REVIEW

**Comment by Sayakie** [comment]
We have to replace accessing methods modifier before exposing the raw trigger instance.

For instance, clients can set trigger script by calling `#setScript(String)` and then can reinitialize the whole trigger with `#init()` method.
Some points may be try to save triggers, so the trigger will be permanently contaminated.

**Comment by Cupelt** [comment]
> We have to replace accessing methods modifier before exposing the raw trigger instance.
> 
> For instance, clients can set trigger script by calling `#setScript(String)` and then can reinitialize the whole trigger with `#init()` method.
> Some points may be try to save triggers, so the trigger will be permanently contaminated.

Oh i see. Then how abowt make a other class and return them?

**Comment by Sayakie** [comment]
> Oh i see. Then how abowt make a other class and return them?

I second this. Exposes `TriggerFacade` class so that clients can use only restricted methods.

**Comment by Cupelt** [comment]
I've implemented it and I think all triggers need Facade classes. but i think there's better way.
what do you think?

**Comment by Cupelt** [comment]
idk, expose raw TriggerInfo

**Comment by wysohn** [comment]
Or we could step back and think about the use cases.

What is the reason that we need to access the trigger instance? In what scenarios we are going to use it? Maybe we can jot it down as a plain text. Like for example, I can write a repeating trigger that can behave differently based on the `autoStart` status, thus, having `this.isAutoStart()` would be beneficial to check that. Well it doesn't sound very useful to me at the moment, but it could be, to some users.

We can move on from there to pin-point what we actually need instead of just randomly creating the classes

**Comment by Cupelt** [comment]
> g

yes, so I've written the code from a line that doesn't have a big impact on trigger task, 
but I'm wondering if there are any factors that could have a big impact that I haven't thought about

**Comment by wysohn** [comment]
> > Or we could step back and think about the use cases.
> > What is the reason that we need to access the trigger instance? In what scenarios we are going to use it? Maybe we can jot it down as a plain text. Like for example, I can write a repeating trigger that can behave differently based on the `autoStart` status, thus, having `this.isAutoStart()` would be beneficial to check that. Well it doesn't sound very useful to me at the moment, but it could be, to some users.
> > We can move on from there to pin-point what we actually need instead of just randomly creating the classes
> 
> yes, so I've made as many lists as possible without having a big impact on trigger function, and I'm wondering if there are any factors that could have a big impact that I haven't thought about

No no, those are codes, not use cases.

Use case is more of a user-centric concept. What is it that people are trying to do, yet TRG doesn't support this?

There is probably something that inspired you to make these changes, and that's a great place to start before writing the code

**Comment by Cupelt** [comment]
> > > Or we could step back and think about the use cases.
> > > What is the reason that we need to access the trigger instance? In what scenarios we are going to use it? Maybe we can jot it down as a plain text. Like for example, I can write a repeating trigger that can behave differently based on the `autoStart` status, thus, having `this.isAutoStart()` would be beneficial to check that. Well it doesn't sound very useful to me at the moment, but it could be, to some users.
> > > We can move on from there to pin-point what we actually need instead of just randomly creating the classes
> > 
> > 
> > yes, so I've made as many lists as possible without having a big impact on trigger function, and I'm wondering if there are any factors that could have a big impact that I haven't thought about
> 
> No no, those are codes, not use cases.
> 
> Use case is more of a user-centric concept. What is it that people are trying to do, yet TRG doesn't support this?
> 
> There is probably something that inspired you to make these changes, and that's a great place to start before writing the code

Oh, I don't know if I understood it correctly. 
That mean does "Why add this to TRG? When does the user use this feature?" right?

sorry my english is terrible

**Pull request closed without merging**
