### PR TITLE
12 New Executors for World Editing

### PR DESCRIPTION
**Pull request by soliddanii**
Every executor has been tested and works correctly. Feel free to edit them if you want. They are all in a folder called WORLD.

Executors and parameters:

#DOORCLOSE    [location<location or number number number>]
Closes the door (or trapdoor or fence) at the given location.

#DOOROPEN     [location<location or number number number>]
Opens the door at the given location.

#DOORTOGGLE [location<location or number number number>]
Toggles the door state at a given location.

#DROPITEM [item<string or number>, quantity<number>, Enchantments<string>, location<location or number number number>]
Spawns a item in the given location.
Every item name must be one from the materials enum: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Enchantments must be "none" or a list of enchantments formated in a string like so: "enchantment1:level,enchantment2:level...". Example: "durability:2,luck:1". Every enchantment name must be a name from the enum in: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
Knowing what enchantments and levels go with what items is the user responsability.

#FALLINGBLOCK [block<string or number>, location<location or number number number>] or [block<string or number>, blockData<number>, location<location or number number number>]
Spawns a block that falls like sand of gravel. Again, of provided a block name it must be from the Materials enum.

#ITEMFRAMEROTATE [Rotation<string>, location<location or number number number>]
Rotates the item inside the itemframe at the given location.
Rotation must be a string from the enum: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Rotation.html
Ex: #ITEMFRAMEROTATE "CLOCKWISE" 230 71 259

#ITEMFRAMESET [item<string or number>, location<location or number number number>] or [item<string or number>, itemData<number>, location<location or number number number>]
Sets the item inside the itemframe at the given location.
Ex: #ITEMFRAMESET "dirt" 2 230 71 259

#LEVEROFF [location<location or number number number>]
Sets the lever state in the given location to off. The redstone circuits connected to it respond accordingly.

#LEVERON [location<location or number number number>]
Sets the lever state in the given location to on. The redstone circuits connected to it respond accordingly.

#LEVERTOGGLE [location<location or number number number>]
Toggles the lever state in the given location. The redstone circuits connected to it respond accordingly.

#SETBLOCK [block<string or number>, location<location or number number number>] or [block<string or number>, blockData<number>,  location<location or number number number>]
Changes the block type and data (if provided) in the given location. Data is optional. If using block name, it must be a material enum.

#SIGNEDIT [Line<number>, Text<string>, location<location or number number number>]
Sets the text of the sign at line. First line is line 0. Accepts formatting with &a, &k, &l....
Ex: #SIGNEDIT 0 "&aHello there" 230 71 259

### CODE REVIEW

**Comment by wysohn** [comment]
Sweet!

Let me finish #8 real quick, so I can test them briefly before merging.

**Comment by soliddanii** [comment]
I saw you added support for itemstack and enchantment validation in dropitem, nice!
Did you test all of them? Having the testing command would be of great help hahah 👍

**Comment by wysohn** [comment]
Oh yeah I tested all the DOOR executors. They are working like a charm. Great work!

Also tested FallingBlock and it works great as well.

Not sure about the ItemFrameRotation as it never worked for me.

Still testing, yet I'm pretty sure they are all good to go :)

I will continue tommorow as I have to go to bed.

I will upload some samples in More Examples for future reference before sleep.

**Comment by soliddanii** [comment]
Make sure you set the location of the actual itemframe, not the location of the block holding the itemframe. And the itemframe must have an item inside obviously. It should work :)
    #WORLD:ITEMFRAMEROTATE "CLOCKWISE" x y z

**Comment by wysohn** [comment]
Tested all and confirmed everything.

Except I couldn't really confirm the frame related Executors

But if it worked for you, lets leave it that way

**Comment by wysohn** [comment]
Hi,

I need you to ready for the new update for ExecutorManager

I'm going to override any Executor that is duplicating with the Executors present in the .jar file.

This is because leaving outdated Executor can be bad for the users who doesn't know how things work. Lets keep it this way from now on.

So if you have anything that is not updated on Executor folder, make sure to make a back-up or make pull request.

**Pull request merged**
