### PR TITLE
Resolved #261, added String support for IS Statement

### LINKED ISSUE #261: Allow strings on the right side of an IS expression.
The current implementation of IS requires the right side to be an imported class.
If we were to also allow simple class names, it would have 2 benefits:

- The code becomes much more concise without the imports.
- Dynamically determining which type to test for is possible.

Manual importing is still useful for cases where the simple class name is ambiguous.

### PR DESCRIPTION
**Pull request by rkdrns4747**
Resolved #261, added String support for IS Statement.
simple In-game test was completed.

### CODE REVIEW

**Comment by wysohn** [comment]
@rkdrns4747 

Can you write a unit test for this?

It would be easier than testing it in-game manually

Modify the TestIntepreter.java
https://github.com/TriggerReactor/TriggerReactor/blob/master/core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java

**Review by wysohn — CHANGES_REQUESTED** [review]
Can you write a unit test for this?

It would be easier than testing it in-game manually

Modify the TestIntepreter.java
https://github.com/TriggerReactor/TriggerReactor/blob/master/core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java

**Comment by rkdrns4747** [comment]
Alright :)

**Review by gerzytet — CHANGES_REQUESTED** [review]
It doesn't address cases where the class and the name are seperated by more than one level of inheritance.  For example, Player implements HumanEntity implements LivingEntity...  so Player IS "LivingEntity" should be true, but you don't test for more than one layer of inheritance.

you're going to end up needing a recursive function

**Comment by rkdrns4747** [comment]
In progress.

**Comment by rkdrns4747** [comment]
@wysohn @gerzytet done. If you guys look at the code in f02fa68 , I wrote why I used 'for statement' twice in checking interfaces.

**Review by wysohn — APPROVED** [review]
looks good to me. Any thoughts? @gerzytet

**Comment by gerzytet** [comment]
This will probably work for most objects, but it will still only handle 2 layers of hierarchy
Some classes have 5-6 layers.
You need to write it so that it handles any number of layers.
My suggestion for doing this is to write a recursive function.
Psudocode:
```
public boolean isInstance(String className, Class superclass)
if className and superClass's name match
  return true
endif
for each parent of superClass:
  if isInstance(className, parent)
    return true
  endif
endfor
return false
```

**Comment by rkdrns4747** [comment]
@gerzytet isnt that handled with while statement I used in the code?
    
    while(leftclass != null){
        if(check)
            break;
        else
            leftclass = leftclass.getSuperclass()
    }

**Comment by gerzytet** [comment]
@rkdrns4747 
You code does appear to handle normal class inheritance correctly, but not more than 2 layers of interfaces.
If you had
```
interface A
interface  B implements A
interface  C implements B
interface  D implements C
```
and an instance of D, your code would not recognize it an an instance of A, because it only searches 2 layers of interfaces:
```
                       Class<?>[] tempInterfaces = tempLeftClass.getInterfaces();
                        craftCheck:
                        if(tempInterfaces != null) {
                            for (Class<?> clazz : tempInterfaces) {
                                if (clazz.getSimpleName().equalsIgnoreCase(className)) {
                                    interfacesCheck = true;
                                    break;
                                }
                                Class<?>[] itfcs = clazz.getInterfaces();
                                if(itfcs != null){
                                    generalCheck:
                                    for(Class<?> itfc : itfcs){
                                        if (itfc.getSimpleName().equalsIgnoreCase(className)) {
                                            interfacesCheck = true;
                                            break craftCheck;
                                        }else {
                                            continue;
                                        }
                                    }
                                }
                            }
                        }
```
Your superclass checks wouldn't work for these chains of interfaces, becuase Class objects representing interfaces return null for getSuperClass()

**Comment by wysohn** [comment]
@rkdrns4747 
Any update on this?

This might be helpful as a reference: https://github.com/TriggerReactor/TriggerReactor/pull/288/commits/f0ea5044360490e618166ad1da633a6d04f03ef6

**Comment by rkdrns4747** [comment]
This will be re-opened soon

**Pull request closed without merging**
