### PR TITLE
A new executor, and a renewed executor

### PR DESCRIPTION
**Pull request by rkdrns4747**
### This #KICK Executor is simply used to kick player.

**1)** kick sender - Not giving any argument

    #KICK

**2)** kick sender with custom kick message - giving only one argument

    #KICK "You are kicked"

**3)** kick specific player - giving only one argument

    #KICK player("Pro_Snape")

**4)** kick specific player with custom kick message - giving two arguments

    #KICK player("Pro_Snape") "You are kicked lmao"

---

### This makes #CLEARCHAT able to accept Player instance.
**1)** Clear specific player's chat

    #CLEARCHAT player("Pro_Snape")

### CODE REVIEW

**Comment by rkdrns4747** [comment]
> Sorry about the close-reopen, that was an accident

Fixed what you're recommended. Hope these Executors work perfect.

**Comment by rkdrns4747** [comment]
@wysohn
kk, got it.
btw I got error while testing executor in Trivis, but I cannot see details of the error. Is there any way to see detailed information about an error?

**Comment by rkdrns4747** [comment]
@wyshon 
I ran gradle build task in IntelliJ, but It says build finished without any errors. 
Is this possible thing that build result is differrent between travis CI's build and IntelliJ's build?

**Comment by rkdrns4747** [comment]
@wysohn 

yea I'm using jdk1.8. and also project sdk is jdk 1.8

**Comment by rkdrns4747** [comment]
@wysohn kk. I'll try that after my school ended.

**Comment by rkdrns4747** [comment]
@wysohn I checked it, but there isn't even 'run ~~' button when I right-click the file.

**Comment by rkdrns4747** [comment]
ahh, now I know how Mockito works. thanks for help!

**Comment by rkdrns4747** [comment]
@wysohn
Can I ask you help one more? I got BUILD  COMPLETE on IntelliJ, but I got error while building on Travis, ParserExeception.

**Comment by rkdrns4747** [comment]
@gerzytet ohh, that's why I don't feel good when I make new Executor, PlaceHolder. Thanks for reminding :)

also, I'll fix them a few hours later.

**Comment by wysohn** [comment]
There must be a way in Intellij to test it locally

At least you can build it with gradle then it will throw errors in console as messages

We can't do much but assume that ECMAExeption is indeed thrown by the KICK executor itself, but we never know the details.

At least the code seems to be working, but maybe the message part of asserError() is not exactly matching with the one in the test cases.

**Comment by rkdrns4747** [comment]
@wysohn I got passed KICK.js test on Travis too, but my the actual problem is testClearChat() one that I recently added. 
If assertError() 's message doesn't matched to Executor message well, It must have given me error when I build on my local device.

**Comment by wysohn** [comment]
Apparently, that's a new error

If ParserException is thrown, I assume you have some syntax error in the CLEARCHAT executor

It's not related to the test

**Comment by rkdrns4747** [comment]
@wysohn oh kk, I'll check it thx

**Comment by wysohn** [comment]
Looks good to me! 

Great work

**Comment by wysohn** [comment]
@rkdrns4747 
Please also update Wiki accordingly.

**Comment by rkdrns4747** [comment]
Moved done, due to being published in ver2.2.1

**Pull request merged**
