### PR TITLE
Location serialization support for Legacy version. (master base)

### PR DESCRIPTION
**Pull request by rkdrns4747**

### CODE REVIEW

**Review by wysohn — CHANGES_REQUESTED** [review]
You must register any custom ConfigurationSerializable into ConfigurationSerialization class

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/configuration/serialization/ConfigurationSerialization.html#registerClass(java.lang.Class)

**Comment by rkdrns4747** [comment]
@wysohn is it ok placing that on 'onEnable' in [TriggerReactor](https://triggerreactor.github.io/io/github/wysohn/triggerreactor/bukkit/main/TriggerReactor.html#onEnable--)

**Comment by wysohn** [comment]
@rkdrns4747 
Hmm why not
Let's see how it look
Just push it so I can see

**Review by wysohn — APPROVED** [review]
looking good to me

**Comment by wysohn** [comment]
@rkdrns4747 
You can go ahead and merge it

**Comment by rkdrns4747** [comment]
Alright Great 👍

**Pull request merged**
